# ansible/roles/lxc-container-setup/tasks/configure-docker.yml
---
- name: Install Docker
  apt:
    name: docker-ce
    state: present
  become: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Log in to container registry
  shell: |
    echo "{{ container_registry_token }}" | docker login {{ registry_url }} --username username --password-stdin
  become: yes
  when: container_registry_token is defined

- name: Pull Docker image
  docker_image:
    name: "{{ docker_image_path }}"
    source: pull
  become: yes
  when: docker_image_path is defined
